
#2001

```{r}
data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2001/VOSClim_GTS_jan_2001.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.jan2001 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.jan2001) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2001/VOSClim_GTS_feb_2001.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.feb2001 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.feb2001) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2001/VOSClim_GTS_mar_2001.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.mar2001 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.mar2001) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")





data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2001/VOSClim_GTS_apr_2001.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.apr2001 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.apr2001) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")





data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2001/VOSClim_GTS_may_2001.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.may2001 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.may2001) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")





data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2001/VOSClim_GTS_jun_2001.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.jun2001 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.jun2001) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")





data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2001/VOSClim_GTS_jul_2001.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.jul2001 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.jul2001) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2001/VOSClim_GTS_aug_2001.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.aug2001 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.aug2001) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")





data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2001/VOSClim_GTS_sep_2001.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.sep2001 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.sep2001) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2001/VOSClim_GTS_oct_2001.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.oct2001 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.oct2001) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2001/VOSClim_GTS_nov_2001.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.nov2001 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.nov2001) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2001/VOSClim_GTS_dec_2001.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.dec2001 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.dec2001) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data.2001 <- rbind(data.clean.jan2001, data.clean.feb2001, data.clean.mar2001, data.clean.apr2001, data.clean.may2001, data.clean.jun2001, data.clean.jul2001, data.clean.aug2001, data.clean.sep2001, data.clean.oct2001, data.clean.nov2001, data.clean.dec2001)
``` 





#2002

```{r}
data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2002/VOSClim_GTS_jan_2002.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.jan2002 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.jan2002) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")

 


data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2002/VOSClim_GTS_feb_2002.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.feb2002 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.feb2002) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2002/VOSClim_GTS_mar_2002.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.mar2002 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.mar2002) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")





data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2002/VOSClim_GTS_apr_2002.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.apr2002 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.apr2002) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")





data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2002/VOSClim_GTS_may_2002.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.may2002 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.may2002) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")





data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2002/VOSClim_GTS_jun_2002.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.jun2002 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.jun2002) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")





data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2002/VOSClim_GTS_jul_2002.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.jul2002 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.jul2002) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2002/VOSClim_GTS_aug_2002.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.aug2002 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.aug2002) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")





data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2002/VOSClim_GTS_sep_2002.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.sep2002 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.sep2002) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2002/VOSClim_GTS_oct_2002.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.oct2002 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.oct2002) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")





data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2002/VOSClim_GTS_nov_2002.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.nov2002 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.nov2002) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")






data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2002/VOSClim_GTS_dec_2002.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.dec2002 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.dec2002) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



data.2002 <- rbind(data.clean.jan2002, data.clean.feb2002, data.clean.mar2002, data.clean.apr2002, data.clean.may2002, data.clean.jun2002, data.clean.jul2002, data.clean.aug2002, data.clean.sep2002, data.clean.oct2002, data.clean.nov2002, data.clean.dec2002)
``` 




#2003

```{r}
data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2003/VOSClim_GTS_jan_2003.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.jan2003 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.jan2003) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")





data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2003/VOSClim_GTS_feb_2003.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.feb2003 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.feb2003) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")





data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2003/VOSClim_GTS_mar_2003.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.mar2003 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.mar2003) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")









data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2003/VOSClim_GTS_apr_2003.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.apr2003 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.apr2003) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")


#data.clean.apr2003 <- rbind(data.clean.apr2003.1, data.clean.apr2003.2, data.clean.apr2003.3)






data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2003/VOSClim_GTS_may_2003.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.may2003 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.may2003) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")








data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2003/VOSClim_GTS_jun_2003.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.jun2003 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.jun2003) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")






data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2003/VOSClim_GTS_jul_2003.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.jul2003 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.jul2003) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")








data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2003/VOSClim_GTS_aug_2003.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.aug2003 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.aug2003) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")









data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2003/VOSClim_GTS_sep_2003.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.sep2003 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.sep2003) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")







data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2003/VOSClim_GTS_oct_2003.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.oct2003 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.oct2003) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")










data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2003/VOSClim_GTS_nov_2003.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.nov2003 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.nov2003) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")







data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2003/VOSClim_GTS_dec_2003.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.dec2003 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.dec2003) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")






data.2003 <- rbind(data.clean.jan2003, data.clean.feb2003, data.clean.mar2003, data.clean.apr2003, data.clean.may2003, data.clean.jun2003, data.clean.jul2003, data.clean.aug2003, data.clean.sep2003, data.clean.oct2003, data.clean.nov2003, data.clean.dec2003)
```



#2004
```{r}


data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2004/VOSClim_GTS_jan_2004.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.jan2004 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.jan2004) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")





data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2004/VOSClim_GTS_feb_2004.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.feb2004 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.feb2004) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")





data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2004/VOSClim_GTS_mar_2004.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.mar2004 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.mar2004) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")









data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2004/VOSClim_GTS_apr_2004.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.apr2004 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.apr2004) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")







data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2004/VOSClim_GTS_may_2004.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.may2004 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.may2004) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")








data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2004/VOSClim_GTS_jun_2004.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.jun2004 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.jun2004) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")






data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2004/VOSClim_GTS_jul_2004.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.jul2004 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.jul2004) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")








data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2004/VOSClim_GTS_aug_2004.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.aug2004 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.aug2004) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")









data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2004/VOSClim_GTS_sep_2004.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.sep2004 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.sep2004) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")







data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2004/VOSClim_GTS_oct_2004.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.oct2004 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.oct2004) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")











data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2004/VOSClim_GTS_nov_2004.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.nov2004 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.nov2004) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")







data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2004/VOSClim_GTS_dec_2004.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.dec2004 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.dec2004) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")






data.2004 <- rbind(data.clean.jan2004, data.clean.feb2004, data.clean.mar2004, data.clean.apr2004, data.clean.may2004, data.clean.jun2004, data.clean.jul2004, data.clean.aug2004, data.clean.sep2004, data.clean.oct2004, data.clean.nov2004, data.clean.dec2004)
```



```{r}

# combined 2001-2004 (and Jan 1 of 2005)

data.upto.2004 <- rbind(data.2001, data.2002, data.2003, data.2004)

#convert to correct decimal
data.upto.2004$LAT <- data.upto.2004$LAT/100

```

```{r}

# get rid of non numerics in LON
data.upto.2004$LON=as.numeric(data.upto.2004$LON)

# narrow down to latitudes/longitudes of southeast asia
data.upto.2004 <- subset(data.upto.2004, LAT >= -6.00 & LAT <= 18.00)
data.upto.2004 <- subset(data.upto.2004, LON >= 108 & LON <= 136)

```
```{r}
# Make AT and SST numeric then display in correct decimal
data.upto.2004$AT=as.numeric(data.upto.2004$AT)
data.upto.2004$AT <- data.upto.2004$AT/10
data.upto.2004$SST=as.numeric(data.upto.2004$SST)
data.upto.2004$SST <- data.upto.2004$SST/10

```


#2006

```{r}
data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2006/VOSClim_GTS_jan_2006.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.jan2006 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.jan2006) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")

 


data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2006/VOSClim_GTS_feb_2006.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.feb2006 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.feb2006) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2006/VOSClim_GTS_mar_2006.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.mar2006 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.mar2006) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")





data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2006/VOSClim_GTS_apr_2006.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.apr2006 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.apr2006) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")





data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2006/VOSClim_GTS_may_2006.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.may2006 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.may2006) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")





data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2006/VOSClim_GTS_jun_2006.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.jun2006 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.jun2006) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")





data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2006/VOSClim_GTS_jul_2006.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.jul2006 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.jul2006) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2006/VOSClim_GTS_aug_2006.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.aug2006 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.aug2006) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")





data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2006/VOSClim_GTS_sep_2006.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.sep2006 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.sep2006) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2006/VOSClim_GTS_oct_2006.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.oct2006 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.oct2006) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")





data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2006/VOSClim_GTS_nov_2006.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.nov2006 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.nov2006) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")






data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2006/VOSClim_GTS_dec_2006.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.dec2006 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.dec2006) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



data.2006 <- rbind(data.clean.jan2006, data.clean.feb2006, data.clean.mar2006, data.clean.apr2006, data.clean.may2006, data.clean.jun2006, data.clean.jul2006, data.clean.aug2006, data.clean.sep2006, data.clean.oct2006, data.clean.nov2006, data.clean.dec2006)
``` 




#2007

```{r}
data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2007/VOSClim_GTS_jan_2007.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.jan2007 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.jan2007) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")





data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2007/VOSClim_GTS_feb_2007.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.feb2007 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.feb2007) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")





data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2007/VOSClim_GTS_mar_2007.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.mar2007 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.mar2007) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")









data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2007/VOSClim_GTS_apr_2007.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.apr2007 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.apr2007) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")


#data.clean.apr2007 <- rbind(data.clean.apr2007.1, data.clean.apr2007.2, data.clean.apr2007.3)






data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2007/VOSClim_GTS_may_2007.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.may2007 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.may2007) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")








data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2007/VOSClim_GTS_jun_2007.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.jun2007 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.jun2007) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")






data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2007/VOSClim_GTS_jul_2007.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.jul2007 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.jul2007) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")








data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2007/VOSClim_GTS_aug_2007.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.aug2007 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.aug2007) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")









data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2007/VOSClim_GTS_sep_2007.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.sep2007 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.sep2007) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")







data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2007/VOSClim_GTS_oct_2007.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.oct2007 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.oct2007) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")










data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2007/VOSClim_GTS_nov_2007.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.nov2007 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.nov2007) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")







data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2007/VOSClim_GTS_dec_2007.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.dec2007 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.dec2007) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")






data.2007 <- rbind(data.clean.jan2007, data.clean.feb2007, data.clean.mar2007, data.clean.apr2007, data.clean.may2007, data.clean.jun2007, data.clean.jul2007, data.clean.aug2007, data.clean.sep2007, data.clean.oct2007, data.clean.nov2007, data.clean.dec2007)
```



#2008
```{r}


data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2008/VOSClim_GTS_jan_2008.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.jan2008 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.jan2008) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")





data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2008/VOSClim_GTS_feb_2008.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.feb2008 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.feb2008) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")





data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2008/VOSClim_GTS_mar_2008.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.mar2008 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.mar2008) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")









data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2008/VOSClim_GTS_apr_2008.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.apr2008 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.apr2008) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")







data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2008/VOSClim_GTS_may_2008.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.may2008 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.may2008) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")








data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2008/VOSClim_GTS_jun_2008.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.jun2008 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.jun2008) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")






data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2008/VOSClim_GTS_jul_2008.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.jul2008 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.jul2008) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")








data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2008/VOSClim_GTS_aug_2008.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.aug2008 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.aug2008) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")









data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2008/VOSClim_GTS_sep_2008.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.sep2008 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.sep2008) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")







data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2008/VOSClim_GTS_oct_2008.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.oct2008 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.oct2008) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")











data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2008/VOSClim_GTS_nov_2008.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.nov2008 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.nov2008) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")







data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2008/VOSClim_GTS_dec_2008.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

data.clean.dec2008 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(data.clean.dec2008) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")






data.2008 <- rbind(data.clean.jan2008, data.clean.feb2008, data.clean.mar2008, data.clean.apr2008, data.clean.may2008, data.clean.jun2008, data.clean.jul2008, data.clean.aug2008, data.clean.sep2008, data.clean.oct2008, data.clean.nov2008, data.clean.dec2008)
```



```{r}

# combine 2005-2008 (and Jan 1 of 2009)
datato2008 <- rbind(data.2006, data.2007, data.2008)

#convert to correct decimal
datato2008$LAT <- datato2008$LAT/100

```

```{r}

# get rid of non numerics in LON
datato2008$LON=as.numeric(datato2008$LON)

# narrow down to latitudes/longitudes of southeast asia
#library(dplyr)
datato2008 <- subset(datato2008, LAT >= -6.00 & LAT <= 18.00)
datato2008 <- subset(datato2008, LON >= 108 & LON <= 136)

```

```{r}
# Make AT and SST numeric then display in correct decimal
datato2008$AT=as.numeric(datato2008$AT)
datato2008$AT <- datato2008$AT/10

datato2008$SST=as.numeric(datato2008$SST)
datato2008$SST <- datato2008$SST/10

```


```{r}
#Jan/2009
jan_2009 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2009/VOSClim_GTS_jan_2009.txt")
df <- NULL
for (i in 1:length(jan_2009)) {
  tmp <- jan_2009[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_jan_2009 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_jan_2009) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")


#Feb/2009
feb_2009 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2009/VOSClim_GTS_feb_2009.txt")
df <- NULL
for (i in 1:length(feb_2009)) {
  tmp <- feb_2009[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_feb_2009 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_feb_2009) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



#Mar/2009
mar_2009 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2009/VOSClim_GTS_mar_2009.txt")
df <- NULL
for (i in 1:length(mar_2009)) {
  tmp <- mar_2009[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_mar_2009 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_mar_2009) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")


#Apr/2009
apr_2009 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2009/VOSClim_GTS_apr_2009.txt")
df <- NULL
for (i in 1:length(apr_2009)) {
  tmp <- apr_2009[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_apr_2009 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_apr_2009) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")


#May/2009
may_2009 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2009/VOSClim_GTS_may_2009.txt")
df <- NULL
for (i in 1:length(may_2009)) {
  tmp <- may_2009[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_may_2009 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_may_2009) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



#Jun/2009
jun_2009 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2009/VOSClim_GTS_jun_2009.txt")
df <- NULL
for (i in 1:length(jun_2009)) {
  tmp <- jun_2009[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_jun_2009 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_jun_2009) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")


#Jul/2009
jul_2009 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2009/VOSClim_GTS_jul_2009.txt")
df <- NULL
for (i in 1:length(jul_2009)) {
  tmp <- jul_2009[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_jul_2009 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_jul_2009) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")


#Aug/2009
aug_2009 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2009/VOSClim_GTS_aug_2009.txt")
df <- NULL
for (i in 1:length(aug_2009)) {
  tmp <- aug_2009[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_aug_2009 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_aug_2009) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")


#Sep/2009
sep_2009 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2009/VOSClim_GTS_sep_2009.txt")
df <- NULL
for (i in 1:length(sep_2009)) {
  tmp <- sep_2009[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_sep_2009 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_sep_2009) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



#Oct/2009
oct_2009 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2009/VOSClim_GTS_oct_2009.txt")
df <- NULL
for (i in 1:length(oct_2009)) {
  tmp <- oct_2009[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_oct_2009 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_oct_2009) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



#Nov/2009
nov_2009 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2009/VOSClim_GTS_nov_2009.txt")
df <- NULL
for (i in 1:length(nov_2009)) {
  tmp <- nov_2009[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_nov_2009 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_nov_2009) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



#Dec/2009
dec_2009 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2009/VOSClim_GTS_dec_2009.txt")
df <- NULL
for (i in 1:length(dec_2009)) {
  tmp <- dec_2009[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_dec_2009 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_dec_2009) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")
```

#2010
```{r}

#Jan/2010
jan_2010 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2010/VOSClim_GTS_jan_2010.txt")
df <- NULL
for (i in 1:length(jan_2010)) {
  tmp <- jan_2010[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_jan_2010 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_jan_2010) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")


#Feb/2010
feb_2010 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2010/VOSClim_GTS_feb_2010.txt")
df <- NULL
for (i in 1:length(feb_2010)) {
  tmp <- feb_2010[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_feb_2010 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_feb_2010) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")

#Mar/2010
mar_2010 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2010/VOSClim_GTS_mar_2010.txt")
df <- NULL
for (i in 1:length(mar_2010)) {
  tmp <- mar_2010[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_mar_2010 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_mar_2010) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



#Apr/2010
apr_2010 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2010/VOSClim_GTS_apr_2010.txt")
df <- NULL
for (i in 1:length(apr_2010)) {
  tmp <- apr_2010[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_apr_2010 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_apr_2010) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")


#May/2010
may_2010 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2010/VOSClim_GTS_may_2010.txt")
df <- NULL
for (i in 1:length(may_2010)) {
  tmp <- may_2010[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_may_2010 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_may_2010) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



#Jun/2010
jun_2010 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2010/VOSClim_GTS_jun_2010.txt")
df <- NULL
for (i in 1:length(jun_2010)) {
  tmp <- jun_2010[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_jun_2010 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_jun_2010) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



#Jul/2010
jul_2010 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2010/VOSClim_GTS_jul_2010.txt")
df <- NULL
for (i in 1:length(jul_2010)) {
  tmp <- jul_2010[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_jul_2010 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_jul_2010) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



#Aug/2010
aug_2010 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2010/VOSClim_GTS_aug_2010.txt")
df <- NULL
for (i in 1:length(aug_2010)) {
  tmp <- aug_2010[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_aug_2010 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_aug_2010) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



#Sep/2010
sep_2010 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2010/VOSClim_GTS_sep_2010.txt")
df <- NULL
for (i in 1:length(sep_2010)) {
  tmp <- sep_2010[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_sep_2010 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_sep_2010) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



#Oct/2010
oct_2010 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2010/VOSClim_GTS_oct_2010.txt")
df <- NULL
for (i in 1:length(oct_2010)) {
  tmp <- oct_2010[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_oct_2010 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_oct_2010) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



#Nov/2010
nov_2010 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2010/VOSClim_GTS_nov_2010.txt")
df <- NULL
for (i in 1:length(nov_2010)) {
  tmp <- nov_2010[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_nov_2010 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_nov_2010) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



#Dec/2010
dec_2010 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2010/VOSClim_GTS_dec_2010.txt")
df <- NULL
for (i in 1:length(dec_2010)) {
  tmp <- dec_2010[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_dec_2010 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_dec_2010) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")
```

#2011
```{r}
#Jan/2011
jan_2011 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2011/VOSClim_GTS_jan_2011.txt")
df <- NULL
for (i in 1:length(jan_2011)) {
  tmp <- jan_2011[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_jan_2011 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_jan_2011) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")


#Feb/2011
feb_2011 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2011/VOSClim_GTS_feb_2011.txt")
df <- NULL
for (i in 1:length(feb_2011)) {
  tmp <- feb_2011[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_feb_2011 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_feb_2011) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")
```

```{r}
#Mar/2011
mar_2011 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2011/VOSClim_GTS_mar_2011.txt")
df <- NULL
for (i in 1:length(mar_2011)) {
  tmp <- mar_2011[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_mar_2011 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_mar_2011) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")


#Apr/2011
apr_2011 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2011/VOSClim_GTS_apr_2011.txt")
df <- NULL
for (i in 1:length(apr_2011)) {
  tmp <- apr_2011[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_apr_2011 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_apr_2011) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



#May/2011
may_2011 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2011/VOSClim_GTS_may_2011.txt")
df <- NULL
for (i in 1:length(may_2011)) {
  tmp <- may_2011[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_may_2011 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_may_2011) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



#Jun/2011
jun_2011 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2011/VOSClim_GTS_jun_2011.txt")
df <- NULL
for (i in 1:length(jun_2011)) {
  tmp <- jun_2011[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_jun_2011 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_jun_2011) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



#Jul/2011
jul_2011 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2011/VOSClim_GTS_jul_2011.txt")
df <- NULL
for (i in 1:length(jul_2011)) {
  tmp <- jul_2011[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_jul_2011 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_jul_2011) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



#Aug/2011
aug_2011 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2011/VOSClim_GTS_aug_2011.txt")
df <- NULL
for (i in 1:length(aug_2011)) {
  tmp <- aug_2011[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_aug_2011 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_aug_2011) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



#Sep/2011
sep_2011 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2011/VOSClim_GTS_sep_2011.txt")
df <- NULL
for (i in 1:length(sep_2011)) {
  tmp <- sep_2011[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_sep_2011 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_sep_2011) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



#Oct/2011
oct_2011 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2011/VOSClim_GTS_oct_2011.txt")
df <- NULL
for (i in 1:length(oct_2011)) {
  tmp <- oct_2011[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_oct_2011 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_oct_2011) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



#Nov/2011
nov_2011 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2011/VOSClim_GTS_nov_2011.txt")
df <- NULL
for (i in 1:length(nov_2011)) {
  tmp <- nov_2011[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_nov_2011 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_nov_2011) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



#Dec/2011
dec_2011 <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2011/VOSClim_GTS_dec_2011.txt")
df <- NULL
for (i in 1:length(dec_2011)) {
  tmp <- dec_2011[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

clean_dec_2011 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(clean_dec_2011) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")
```




```{r}
#Combine each month to a year
buoy_2009 <- rbind(clean_jan_2009,clean_feb_2009,clean_mar_2009,clean_apr_2009,clean_may_2009,clean_jun_2009,clean_jul_2009,clean_aug_2009,clean_sep_2009,clean_oct_2009,clean_nov_2009,clean_dec_2009)

buoy_2010 <- rbind(clean_jan_2010,clean_feb_2010,clean_mar_2010,clean_apr_2010,clean_may_2010,clean_jun_2010,clean_jul_2010,clean_aug_2010,clean_sep_2010,clean_oct_2010,clean_nov_2010,clean_dec_2010)

buoy_2011 <- rbind(clean_jan_2011,clean_feb_2011,clean_mar_2011,clean_apr_2011,clean_may_2011,clean_jun_2011,clean_jul_2011,clean_aug_2011,clean_sep_2011,clean_oct_2011,clean_nov_2011,clean_dec_2011)

#buoy_2012 <- rbind(clean_jan_2012,clean_feb_2012,clean_mar_2012,clean_apr_2012,clean_may_2012,clean_jun_2012,clean_jul_2012,clean_aug_2012,clean_sep_2012,clean_oct_2012,clean_nov_2012,clean_dec_2012)
```
```{r}
#combine 4 years
buoy_09_11$LON=as.numeric(buoy_09_11$LON)
buoy_09_11$LAT=as.numeric(buoy_09_11$LAT)
buoy_09_11 <- rbind(buoy_2009, buoy_2010,buoy_2011)
buoy_09_11$LAT <- buoy_09_11$LAT/100
buoy_09_11$AT <- buoy_09_11$AT/10
buoy_09_11$SST <- buoy_09_11$SST/10


buoy_09_11 <- subset(buoy_09_11, LAT >= -6.00 & LAT <= 18.00)
buoy_09_11 <- subset(buoy_09_11, LON >= 108 & LON <= 136)
```

```{r}
data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2016/VOSClim_GTS_jan_2016.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

jan16 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(jan16) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2016/VOSClim_GTS_feb_2016.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

feb16 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(feb16) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2016/VOSClim_GTS_mar_2016.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

mar16 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(mar16) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2016/VOSClim_GTS_apr_2016.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

apr16 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(apr16) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2016/VOSClim_GTS_may_2016.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

may16 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(may16) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")


data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2016/VOSClim_GTS_jun_2016.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

jun16 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(jun16) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2016/VOSClim_GTS_jul_2016.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

jul16 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(jul16) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2016/VOSClim_GTS_aug_2016.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

aug16 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(aug16) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2016/VOSClim_GTS_sep_2016.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

sep16 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(sep16) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")


data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2016/VOSClim_GTS_oct_2016.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

oct16 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(oct16) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2016/VOSClim_GTS_nov_2016.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

nov16 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(nov16) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2016/VOSClim_GTS_dec_2016.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

dec16 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(dec16) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")

```

# 2015
```{r}
data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2015/VOSClim_GTS_jan_2015.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

jan15 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(jan15) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2015/VOSClim_GTS_feb_2015.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}
feb15 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(feb15) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2015/VOSClim_GTS_mar_2015.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

mar15 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(mar15) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")
```

```{r}
data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2015/VOSClim_GTS_apr_2015.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

apr15 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(apr15) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")


data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2015/VOSClim_GTS_may_2015.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

may15 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(may15) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2015/VOSClim_GTS_jun_2015.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

jun15 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(jun15) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2015/VOSClim_GTS_jul_2015.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

jul15 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(jul15) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2015/VOSClim_GTS_aug_2015.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}

aug15 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(aug15) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2015/VOSClim_GTS_sep_2015.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}
sep15 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(sep15) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2015/VOSClim_GTS_oct_2015.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}
oct15 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(oct15) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2015/VOSClim_GTS_nov_2015.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}
nov15 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(nov15) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2015/VOSClim_GTS_dec_2015.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}
dec15 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(dec15) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")
```

#2014
```{r}
data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2014/VOSClim_GTS_jan_2014.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}
jan14 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(jan14) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2014/VOSClim_GTS_feb_2014.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}
feb14 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(feb14) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2014/VOSClim_GTS_mar_2014.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}
mar14 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(mar14) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2014/VOSClim_GTS_apr_2014.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}
apr14 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(apr14) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2014/VOSClim_GTS_may_2014.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}
may14 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(may14) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2014/VOSClim_GTS_jun_2014.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}
jun14 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(jun14) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2014/VOSClim_GTS_jul_2014.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}
jul14 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(jul14) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2014/VOSClim_GTS_aug_2014.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}
aug14 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(aug14) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2014/VOSClim_GTS_sep_2014.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}
sep14 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(sep14) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2014/VOSClim_GTS_oct_2014.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}
oct14 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(oct14) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2014/VOSClim_GTS_nov_2014.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}
nov14 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(nov14) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2014/VOSClim_GTS_dec_2014.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}
dec14 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(dec14) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")


```

#2013
```{r}
data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2013/VOSClim_GTS_jan_2013.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}
jan13 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(jan13) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2013/VOSClim_GTS_feb_2013.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}
feb13 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(feb13) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2013/VOSClim_GTS_mar_2013.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}
mar13 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(mar13) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2013/VOSClim_GTS_apr_2013.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}
apr13 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(apr13) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2013/VOSClim_GTS_may_2013.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}
may13 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(may13) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2013/VOSClim_GTS_jun_2013.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}
jun13 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(jun13) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2013/VOSClim_GTS_jul_2013.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}
jul13 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(jul13) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2013/VOSClim_GTS_aug_2013.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}
aug13 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(aug13) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2013/VOSClim_GTS_sep_2013.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}
sep13 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(sep13) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2013/VOSClim_GTS_oct_2013.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}
oct13 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(oct13) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")



data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2013/VOSClim_GTS_nov_2013.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}
nov13 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(nov13) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")




data <- readLines("https://www1.ncdc.noaa.gov/pub/data/vosclim/2013/VOSClim_GTS_dec_2013.txt")

df <- NULL
for (i in 1:length(data)) {
  tmp <- data[i]
  subtmp <- paste0(substr(tmp, 1, 21), substr(tmp, 69, 73), substr(tmp, 84, 89))
  df <- rbind(df, subtmp)
}
dec13 <- read.fwf(textConnection(df), widths=c(4,2,2,4,5,4,1,4,2,4))
names(dec13) <- c("YR", "MO", "DY", "HR", "LAT", "LON", "IT", "AT", "SI", "SST")
```

```{r}
from13to16 <- rbind(jan13, feb13, mar13, apr13, may13, jun13, jul13, aug13, sep13, oct13, nov13, dec13, jan14, feb14, mar14, apr14, may14, jun14, jul14, aug14, sep14, oct14, nov14, dec14, jan15, feb15, mar15, apr15, may15, jun15, jul15, aug15, sep15, oct15, nov15, dec15,jan16, feb16, mar16, apr16, may16, jun16, jul16, aug16, sep16, oct16, nov16, dec16)

```

```{r}
#from13to16 <- lapply(from13to16, function(x) as.numeric(as.character(x)))
from13to16$LON=as.numeric(from13to16$LON)
from13to16$LAT=as.numeric(from13to16$LAT)
from13to16$LAT <- from13to16$LAT/100
from13to16$AT <- from13to16$AT/10
from13to16$SST <- from13to16$SST/10
```

```{r}
library(dplyr)
from13to16 <- subset(from13to16, LAT >= -6.00 & LAT <= 18.00)
from13to16 <- subset(from13to16, LON >= 108 & LON <= 136)
#from13to16 %>%
  #filter(LAT  <= 18 & LAT >= -6)%>%
  #filter(LON <= 136 & LON >= 108)

```


#2001-2016
```{r}
# all
data.2001to2016 <- rbind(data.upto.2004, datato2008, buoy_09_11, from13to16)

```

```{r}
# day in posix
library(lubridate)
data.2001to2016$YR = as.numeric(data.2001to2016$YR)
data.2001to2016$MO = as.numeric(data.2001to2016$MO)
data.2001to2016$DY = as.numeric(data.2001to2016$DY)
data.2001to2016$HR = as.numeric(data.2001to2016$HR)

#daytimedf <- data.2001to2016 %>%
#  select(YR, MO, DY, HR, LAT, LON, AT, SST) %>%
#  mutate(daytime = make_datetime(YR, MO, DY))
 #left_join(data.2001to2016)


```
#data.jan2001 <- data.jan2001%>%
#mutate(newtime = abs(HR-1200)) %>%
#group_by(DY)%>%
#summarise(min(newtime)) %>%
#left_join(data.jan2001)

```{r}
#Yes?? (newtime = distance from noon - has min)
daytime.mintime <- daytimedf%>%
select(YR, MO, DY, HR, LAT, LON, AT, SST) %>%
mutate(newtime = abs(HR-1200)) %>%
group_by(daytime = daytimedf$daytime) %>%
slice(which.min(newtime))
```

```{r}
#Omit where AT and SST both NA

pos <- which(is.na(daytime.mintime$AT == TRUE) & is.na(daytime.mintime$SST == TRUE))

daytime.mintime.omits <- daytime.mintime[(-pos), ]


```

# just two columns but has min
#daytime.mintime.2 <- daytimedf%>%
#select(YR, MO, DY, HR, LAT, LON, AT, SST) %>%
#mutate(newtime = abs(HR-1200)) %>%
#group_by(daytime = daytimedf$daytime) %>% 
#summarise(min(newtime)) %>%
#select
#left_join(daytime.mintime)

```{r}
#Datasets for plotting

#Winter
winter_2001 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2001 & MO == 1)
winter_2002 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2002 & MO == 1)
winter_2003 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2003 & MO == 1)
winter_2004 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2004 & MO == 1)
winter_2006 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2006 & MO == 1)
winter_2007 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2007 & MO == 1)
winter_2008 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2008 & MO == 1)
winter_2009 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2009 & MO == 1)
winter_2010 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2010 & MO == 1)
winter_2011 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2011 & MO == 1)
winter_2013 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2013 & MO == 1)
winter_2014 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2014 & MO == 1)
winter_2015 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2015 & MO == 1)
winter_2016 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2016 & MO == 1)
winter <- rbind(winter_2001[1,],winter_2002[1,],winter_2003[1,],winter_2004[1,],winter_2006[1,],winter_2007[1,],winter_2008[1,],winter_2009[1,],winter_2010[1,],winter_2011[1,],winter_2013[1,],winter_2014[1,],winter_2015[1,],winter_2016[1,])
gg1 <- ggplot(data = winter) + geom_point(aes(x = YR, y = AT, color="orange")) + geom_point(aes(x = YR, y = SST, color="blue")) +
  geom_smooth(mapping = aes(x = YR, y = AT, color="orange")) + geom_smooth(mapping = aes(x = YR, y = SST, color="blue")) +   scale_x_discrete( limits = c(2001:2016)) + labs(title="Air Temperature and Sea Surface Temperature Variation in January (2001-2016)", y="Temperature (Celsius)", x="Year", caption="Source: NOAA: VOS")+ scale_colour_manual(name= "",values=c("blue", "orange"), labels=c("Sea Surface Temperature", "Air Temperature")) 
gg1


#Spring
spring_2001 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2001 & MO == 4)
spring_2002 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2002 & MO == 4)
spring_2003 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2003 & MO == 4)
spring_2004 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2004 & MO == 4)
spring_2006 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2006 & MO == 4)
spring_2007 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2007 & MO == 4)
spring_2008 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2008 & MO == 4)
spring_2009 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2009 & MO == 4)
spring_2010 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2010 & MO == 4)
spring_2011 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2011 & MO == 4)
spring_2013 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2013 & MO == 4)
spring_2014 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2014 & MO == 4)
spring_2015 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2015 & MO == 4)
spring_2016 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2016 & MO == 4)
spring <- rbind(spring_2001[1,],spring_2002[1,],spring_2003[1,],spring_2004[1,],spring_2006[1,],spring_2007[1,],spring_2008[1,],spring_2009[1,],spring_2010[1,],spring_2011[1,],spring_2013[1,],spring_2014[1,],spring_2015[1,],spring_2016[1,])
gg2 <-ggplot(data = spring) + geom_point(aes(x = YR, y = AT, color="orange")) + geom_point(aes(x = YR, y = SST, color="blue")) +
  geom_smooth(mapping = aes(x = YR, y = AT, color="orange")) + geom_smooth(mapping = aes(x = YR, y = SST, color="blue")) +   scale_x_discrete( limits = c(2001:2016)) + labs(title="Air Temperature and Sea Surface Temperature Variation in April (2001-2016)", y="Temperature (Celsius)", x="Year", caption="Source: NOAA: VOS")+ scale_colour_manual(name= "",values=c("blue", "orange"), labels=c("Sea Surface Temperature", "Air Temperature"))
gg2


#Summer
summer_2001 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2001 & MO == 7)
summer_2002 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2002 & MO == 7)
summer_2003 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2003 & MO == 7)
summer_2004 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2004 & MO == 7)
summer_2006 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2006 & MO == 7)
summer_2007 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2007 & MO == 7)
summer_2008 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2008 & MO == 7)
summer_2009 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2009 & MO == 7)
summer_2010 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2010 & MO == 7)
summer_2011 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2011 & MO == 7)
summer_2013 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2013 & MO == 7)
summer_2014 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2014 & MO == 7)
summer_2015 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2015 & MO == 7)
summer_2016 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2016 & MO == 7)
summer <- rbind(summer_2001[1,],summer_2002[1,],summer_2003[1,],summer_2004[1,],summer_2006[1,],summer_2007[1,],summer_2008[1,],summer_2009[1,],summer_2010[1,],summer_2011[1,],summer_2013[1,],summer_2014[1,],summer_2015[1,],summer_2016[1,])
gg3<- ggplot(data = summer) + geom_point(aes(x = YR, y = AT, color="orange")) + geom_point(aes(x = YR, y = SST, color="blue")) +
  geom_smooth(mapping = aes(x = YR, y = AT, color="orange")) + geom_smooth(mapping = aes(x = YR, y = SST, color="blue")) +   scale_x_discrete( limits = c(2001:2016)) + labs(title="Air Temperature and Sea Surface Temperature Variation in July (2001-2016)", y="Temperature (Celsius)", x="Year", caption="Source: NOAA: VOS")+ scale_colour_manual(name= "",values=c("blue", "orange"), labels=c("Sea Surface Temperature", "Air Temperature")) 
gg3



#Fall
fall_2001 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2001 & MO == 10)
fall_2002 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2002 & MO == 10)
fall_2003 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2003 & MO == 10)
fall_2004 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2004 & MO == 10)
fall_2006 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2006 & MO == 10)
fall_2007 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2007 & MO == 10)
fall_2008 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2008 & MO == 10)
fall_2009 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2009 & MO == 10)
fall_2010 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2010 & MO == 10)
fall_2011 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2011 & MO == 10)
fall_2013 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2013 & MO == 10)
fall_2014 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2014 & MO == 10)
fall_2015 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2015 & MO == 10)
fall_2016 <- daytime.mintime.omits%>% 
  select(YR,MO,AT,SST)%>%
  filter(YR == 2016 & MO == 10)
fall <- rbind(fall_2001[1,],fall_2002[1,],fall_2003[1,],fall_2004[1,],fall_2006[1,],fall_2007[1,],fall_2008[1,],fall_2009[1,],fall_2010[1,],fall_2011[1,],fall_2013[1,],fall_2014[1,],fall_2015[1,],fall_2016[1,])
gg4 <- ggplot(data = fall) + geom_point(aes(x = YR, y = AT, color="orange")) + geom_point(aes(x = YR, y = SST, color="blue")) +
  geom_smooth(mapping = aes(x = YR, y = AT, color="orange")) + geom_smooth(mapping = aes(x = YR, y = SST, color="blue")) +   scale_x_discrete( limits = c(2001:2016)) + labs(title="Air Temperature and Sea Surface Temperature Variation in October (2001-2016)", y="Temperature (Celsius)", x="Year", caption="Source: NOAA: VOS")+ scale_colour_manual(name= "",values=c("blue", "orange"), labels=c("Sea Surface Temperature", "Air Temperature"))
gg4

```


##time difference and reorder columns
```{r}
daytime.mintime.omits$HR=as.numeric(daytime.mintime.omits$HR)
library(dplyr)
daytime.mintime.omits <- daytime.mintime.omits %>%
  mutate(time_diff = (HR - 1200)/100) %>%
  select(time_diff, LAT, LON, SST, AT, HR, YR, MO, DY)
#daytime.mintime.omits
```



##Posix
```{r}
library(dplyr)
library(lubridate)
daytime.mintime.omits$HR <- daytime.mintime.omits$HR/100
daytime.mintime.omits <- daytime.mintime.omits %>%
  mutate(minute = c(00))%>%
  mutate(newdaytime = make_datetime(YR, MO, DY, HR, minute))
```

#A
```{r}
#??
daytime.mintime.omits <- daytime.mintime.omits %>%
  mutate(abstimedf=abs(HR-12)) 
#for (i in length(daytime.mintime.omits)){
#  if ((daytime.mintime.omits$abstimedf[i] > 6 ){
#    daytime.mintime.omits$abstimedf[i] <- "A"
#  }
#}
daytime.mintime.omits$time_diff <- as.numeric(daytime.mintime.omits$time_diff)
daytime.mintime.omits[daytime.mintime.omits$time_diff > 6|daytime.mintime.omits$time_diff < -6, c("time_diff")] <- "A"


```
